
import type { Metadata } from "next";
import { Mulish, Source_Sans_3 } from "next/font/google"; 
import "./globals.css";

const mulish = Mulish({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const sourceSansPro = Source_Sans_3({
  variable: "--font-source-sans-pro",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Payrous",
  description: "Generated by payrous waitlist",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mulish.variable} ${sourceSansPro.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
